/* Generated by Together */

package com.miw.model;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

@Entity
public class Book {
	
	
	@Id @GeneratedValue
	private int id;
	private String title;
	private String description;
	private String author;
	@JoinColumn(name = "taxGroup", nullable = false)
    @ManyToOne(optional = false, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private VAT vat;
	private double basePrice;
	

	@Transient
	private double price;

	public double getPrice() {
		return price;
	}

	
	public Book() {
		super();
		// TODO Auto-generated constructor stub
	}


	public Book(double price, String title, String description, String author, VAT vat, double basePrice) {
		super();
		this.price = price;
		this.title = title;
		this.description = description;
		this.author = author;
		this.vat = vat;
		this.basePrice = basePrice;
	}
	
	

	public VAT getVat() {
		return vat;
	}


	public void setVat(VAT vat) {
		this.vat = vat;
	}


	public void setPrice(double price) {
		this.price = price;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public double getBasePrice() {
		return basePrice;
	}

	public void setBasePrice(double basePrice) {
		this.basePrice = basePrice;
	}

	@Override
	public String toString() {
		return "Book [id=" + id + ", title=" + title + ", description=" + description + ", author=" + author
				+ ", vat=" + vat + ", basePrice=" + basePrice + ", price=" + price + "]";
	}
}
