/* Generated by Together */

package com.miw.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class VAT {

	@Id
	@GeneratedValue
	private int id;
	private Double value;
	private int taxGroup;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public Double getValue() {
		return value;
	}
	public void setValue(Double value) {
		this.value = value;
	}
	public int getTaxGroup() {
		return taxGroup;
	}
	public void setTaxGroup(int taxGroup) {
		this.taxGroup = taxGroup;
	}
	@Override
	public String toString() {
		return "VAT [id=" + id + ", value=" + value + ", taxGroup=" + taxGroup + "]";
	}

	
	
}
